version: '2'

services:
  database:
    image: postgres:14.4-alpine3.16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=V3geHanu
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data

  web2py:
    build: .
    volumes:
      - ./app:/opt/web2py
    environment:
      - WEB2PY_PASSWORD=931632
      - WEB2PY_ADMIN_SECURITY_BYPASS=true
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web2py
    ports:
      - 8080:80
