version: '3.9'

services:
  database:
    image: postgres:14.4-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=931632#Ha
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/

  web2py:
    build: .
    volumes:
      - ./app:/opt/web2py
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - WEB2PY_PASSWORD=931632
      - WEB2PY_ADMIN_SECURITY_BYPASS=true
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web2py
    ports:
      - 8080:80

volumes: 
  pgdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/database/data
