version: '3.9'

services:
  db:
    build: ./docker/postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/db_data:/var/lib/postgresql/data:z

  web2py:
    build:
      context: ./
      dockerfile: ./docker/web2py/Dockerfile
    volumes:
      - ./app:/opt/web2py
      - ./apps_data:/apps_data
    environment:
      - WEB2PY_PASSWORD=${WEB2PY_PASSWORD}
      - WEB2PY_ADMIN_SECURITY_BYPASS=true
    depends_on:
      - db
    links:
      - db # from inside web2py database host will link us to the database container

  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web2py
    ports:
      - 8080:80

volumes:
  pgdb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/database/data
